[2024-07-04T09:34:23.768+0000] {processor.py:161} INFO - Started process (PID=25) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:34:23.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:34:23.817+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:34:23.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:34:24.329+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:34:24.278+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-04T09:34:24.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:34:24.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.693 seconds
[2024-07-04T09:35:07.990+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:35:07.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:35:08.006+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:35:08.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:35:08.132+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:35:08.086+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-04T09:35:08.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:35:08.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.211 seconds
[2024-07-04T09:35:38.976+0000] {processor.py:161} INFO - Started process (PID=147) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:35:38.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:35:38.980+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:35:38.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:35:39.005+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:35:39.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable hello does not exist'
[2024-07-04T09:35:39.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:35:39.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.049 seconds
[2024-07-04T09:36:09.150+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:36:09.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:36:09.157+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:36:09.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:36:09.220+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:36:09.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:36:09.222+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:36:09.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.106 seconds
[2024-07-04T09:36:40.173+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:36:40.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:36:40.197+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:36:40.196+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:36:40.262+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:36:40.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:36:40.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:36:40.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.119 seconds
[2024-07-04T09:37:10.672+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:37:10.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:37:10.676+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:37:10.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:37:10.702+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:37:10.698+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:37:10.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:37:10.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.050 seconds
[2024-07-04T09:37:41.017+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:37:41.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:37:41.019+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:37:41.019+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:37:41.057+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:37:41.051+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:37:41.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:37:41.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.059 seconds
[2024-07-04T09:38:11.417+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:38:11.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:38:11.420+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:38:11.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:38:11.474+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:38:11.467+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:38:11.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:38:11.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.085 seconds
[2024-07-04T09:38:42.248+0000] {processor.py:161} INFO - Started process (PID=502) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:38:42.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:38:42.250+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:38:42.250+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:38:42.368+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:38:42.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:38:42.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:38:42.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.166 seconds
[2024-07-04T09:39:13.413+0000] {processor.py:161} INFO - Started process (PID=559) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:39:13.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:39:13.416+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:39:13.416+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:39:13.446+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:39:13.440+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:39:13.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:39:13.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.050 seconds
[2024-07-04T09:39:44.244+0000] {processor.py:161} INFO - Started process (PID=618) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:39:44.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:39:44.248+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:39:44.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:39:44.292+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:39:44.278+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:39:44.294+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:39:44.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.076 seconds
[2024-07-04T09:40:14.561+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:40:14.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:40:14.564+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:40:14.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:40:14.586+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:40:14.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:40:14.587+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:40:14.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.042 seconds
[2024-07-04T09:40:44.989+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:40:44.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:40:44.994+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:40:44.993+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:40:45.044+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:40:45.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:40:45.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:40:45.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.085 seconds
[2024-07-04T09:41:15.129+0000] {processor.py:161} INFO - Started process (PID=796) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:41:15.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:41:15.132+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:41:15.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:41:15.158+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:41:15.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:41:15.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:41:15.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.045 seconds
[2024-07-04T09:41:45.562+0000] {processor.py:161} INFO - Started process (PID=855) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:41:45.563+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:41:45.565+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:41:45.565+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:41:45.587+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:41:45.584+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:41:45.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:41:45.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.046 seconds
[2024-07-04T09:42:16.103+0000] {processor.py:161} INFO - Started process (PID=913) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:42:16.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:42:16.108+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:42:16.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:42:16.164+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:42:16.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:42:16.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:42:16.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.086 seconds
[2024-07-04T09:42:46.424+0000] {processor.py:161} INFO - Started process (PID=973) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:42:46.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:42:46.434+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:42:46.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:42:46.478+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:42:46.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:42:46.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:42:46.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.090 seconds
[2024-07-04T09:43:16.892+0000] {processor.py:161} INFO - Started process (PID=1033) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:43:16.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:43:16.896+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:43:16.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:43:16.945+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:43:16.931+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:43:16.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:43:16.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.091 seconds
[2024-07-04T09:43:47.036+0000] {processor.py:161} INFO - Started process (PID=1092) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:43:47.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:43:47.040+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:43:47.040+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:43:47.073+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:43:47.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:43:47.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:43:47.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.057 seconds
[2024-07-04T09:44:17.983+0000] {processor.py:161} INFO - Started process (PID=1151) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:44:17.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:44:17.986+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:44:17.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:44:18.018+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:44:18.011+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:44:18.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:44:18.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.058 seconds
[2024-07-04T09:44:49.019+0000] {processor.py:161} INFO - Started process (PID=1210) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:44:49.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:44:49.033+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:44:49.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:44:49.078+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:44:49.068+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:44:49.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:44:49.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.100 seconds
[2024-07-04T09:45:19.870+0000] {processor.py:161} INFO - Started process (PID=1269) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:45:19.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:45:19.876+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:45:19.875+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:45:19.961+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:45:19.936+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:45:19.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:45:19.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.136 seconds
[2024-07-04T09:45:50.741+0000] {processor.py:161} INFO - Started process (PID=1328) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:45:50.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:45:50.744+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:45:50.743+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:45:50.776+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:45:50.768+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:45:50.777+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:45:50.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.060 seconds
[2024-07-04T09:46:21.050+0000] {processor.py:161} INFO - Started process (PID=1387) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:46:21.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:46:21.054+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:46:21.053+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:46:21.081+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:46:21.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:46:21.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:46:21.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.049 seconds
[2024-07-04T09:46:51.794+0000] {processor.py:161} INFO - Started process (PID=1447) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:46:51.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:46:51.797+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:46:51.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:46:51.829+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:46:51.825+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:46:51.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:46:51.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.051 seconds
[2024-07-04T09:47:22.419+0000] {processor.py:161} INFO - Started process (PID=1507) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:47:22.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:47:22.439+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:47:22.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:47:22.688+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:47:22.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:47:22.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:47:22.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.346 seconds
[2024-07-04T09:47:53.315+0000] {processor.py:161} INFO - Started process (PID=1564) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:47:53.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:47:53.320+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:47:53.319+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:47:53.363+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:47:53.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:47:53.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:47:53.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.087 seconds
[2024-07-04T09:48:24.036+0000] {processor.py:161} INFO - Started process (PID=1623) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:48:24.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:48:24.055+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:48:24.054+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:48:24.122+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:48:24.115+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:48:24.123+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:48:24.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.133 seconds
[2024-07-04T09:48:57.648+0000] {processor.py:161} INFO - Started process (PID=1674) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:48:57.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:48:57.670+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:48:57.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:48:57.757+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:48:57.750+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:48:57.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:48:57.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.164 seconds
[2024-07-04T09:49:27.972+0000] {processor.py:161} INFO - Started process (PID=1732) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:49:27.973+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:49:27.975+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:49:27.974+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:49:27.998+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:49:27.995+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:49:27.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:49:28.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.042 seconds
[2024-07-04T09:49:58.347+0000] {processor.py:161} INFO - Started process (PID=1790) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:49:58.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:49:58.350+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:49:58.349+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:49:58.378+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:49:58.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:49:58.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:49:58.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.048 seconds
[2024-07-04T09:50:29.236+0000] {processor.py:161} INFO - Started process (PID=1849) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:50:29.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:50:29.240+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:50:29.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:50:29.271+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:50:29.265+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:50:29.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:50:29.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.056 seconds
[2024-07-04T09:51:00.000+0000] {processor.py:161} INFO - Started process (PID=1908) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:51:00.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:51:00.010+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:51:00.004+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:51:00.050+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:51:00.043+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:51:00.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:51:00.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.076 seconds
[2024-07-04T09:51:30.215+0000] {processor.py:161} INFO - Started process (PID=1967) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:51:30.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:51:30.220+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:51:30.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:51:30.265+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:51:30.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:51:30.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:51:30.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.077 seconds
[2024-07-04T09:52:00.432+0000] {processor.py:161} INFO - Started process (PID=2026) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:52:00.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:52:00.435+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:52:00.435+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:52:00.461+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:52:00.457+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:52:00.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:52:00.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.053 seconds
[2024-07-04T09:52:31.167+0000] {processor.py:161} INFO - Started process (PID=2086) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:52:31.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:52:31.170+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:52:31.169+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:52:31.199+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:52:31.195+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:52:31.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:52:31.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.049 seconds
[2024-07-04T09:53:02.002+0000] {processor.py:161} INFO - Started process (PID=2145) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:53:02.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:53:02.005+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:53:02.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:53:02.029+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:53:02.025+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:53:02.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:53:02.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.044 seconds
[2024-07-04T09:53:33.046+0000] {processor.py:161} INFO - Started process (PID=2203) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:53:33.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:53:33.051+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:53:33.050+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:53:33.356+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:53:33.333+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:53:33.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:53:33.417+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.377 seconds
[2024-07-04T09:54:13.872+0000] {processor.py:161} INFO - Started process (PID=2266) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:54:13.889+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:54:13.891+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:54:13.891+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:54:14.008+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:54:13.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:54:14.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:54:14.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.230 seconds
[2024-07-04T09:54:44.312+0000] {processor.py:161} INFO - Started process (PID=2324) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:54:44.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:54:44.319+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:54:44.318+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:54:44.381+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:54:44.375+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:54:44.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:54:44.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.102 seconds
[2024-07-04T09:55:14.767+0000] {processor.py:161} INFO - Started process (PID=2381) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:55:14.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:55:14.771+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:55:14.770+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:55:14.818+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:55:14.809+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:55:14.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:55:14.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.089 seconds
[2024-07-04T09:55:44.933+0000] {processor.py:161} INFO - Started process (PID=2440) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:55:44.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:55:44.937+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:55:44.936+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:55:44.976+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:55:44.970+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:55:44.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:55:44.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.065 seconds
[2024-07-04T09:56:16.036+0000] {processor.py:161} INFO - Started process (PID=2499) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:56:16.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:56:16.047+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:56:16.047+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:56:16.170+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:56:16.157+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:56:16.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:56:16.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.191 seconds
[2024-07-04T09:56:46.387+0000] {processor.py:161} INFO - Started process (PID=2558) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:56:46.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:56:46.392+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:56:46.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:56:46.473+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:56:46.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:56:46.474+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:56:46.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.136 seconds
[2024-07-04T09:57:17.207+0000] {processor.py:161} INFO - Started process (PID=2617) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:57:17.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:57:17.225+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:57:17.225+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:57:17.277+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:57:17.269+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:57:17.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:57:17.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.097 seconds
[2024-07-04T09:57:47.732+0000] {processor.py:161} INFO - Started process (PID=2677) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:57:47.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:57:47.736+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:57:47.735+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:57:47.764+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:57:47.759+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:57:47.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:57:47.776+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.051 seconds
[2024-07-04T09:58:18.297+0000] {processor.py:161} INFO - Started process (PID=2736) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:58:18.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:58:18.305+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:58:18.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:58:18.347+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:58:18.342+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:58:18.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:58:18.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.083 seconds
[2024-07-04T09:58:48.481+0000] {processor.py:161} INFO - Started process (PID=2796) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:58:48.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:58:48.484+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:58:48.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:58:48.516+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:58:48.509+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:58:48.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:58:48.529+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.053 seconds
[2024-07-04T09:59:18.732+0000] {processor.py:161} INFO - Started process (PID=2855) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:59:18.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:59:18.735+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:59:18.734+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:59:18.766+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:59:18.761+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:59:18.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:59:18.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.055 seconds
[2024-07-04T09:59:49.403+0000] {processor.py:161} INFO - Started process (PID=2914) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T09:59:49.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T09:59:49.407+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:59:49.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:59:49.437+0000] {logging_mixin.py:188} INFO - [2024-07-04T09:59:49.431+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T09:59:49.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T09:59:49.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.053 seconds
[2024-07-04T10:00:19.724+0000] {processor.py:161} INFO - Started process (PID=2973) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:00:19.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:00:19.728+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:00:19.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:00:19.765+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:00:19.760+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:00:19.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:00:19.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.060 seconds
[2024-07-04T10:00:50.533+0000] {processor.py:161} INFO - Started process (PID=3034) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:00:50.537+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:00:50.545+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:00:50.544+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:00:50.634+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:00:50.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:00:50.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:00:50.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.150 seconds
[2024-07-04T10:01:20.928+0000] {processor.py:161} INFO - Started process (PID=3093) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:01:20.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:01:20.933+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:01:20.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:01:20.993+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:01:20.981+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:01:21.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:01:21.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.122 seconds
[2024-07-04T10:01:51.148+0000] {processor.py:161} INFO - Started process (PID=3153) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:01:51.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:01:51.155+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:01:51.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:01:51.181+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:01:51.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:01:51.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:01:51.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.055 seconds
[2024-07-04T10:02:21.574+0000] {processor.py:161} INFO - Started process (PID=3210) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:02:21.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:02:21.578+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:02:21.577+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:02:21.609+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:02:21.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:02:21.611+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:02:21.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.057 seconds
[2024-07-04T10:02:52.102+0000] {processor.py:161} INFO - Started process (PID=3270) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:02:52.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:02:52.106+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:02:52.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:02:52.150+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:02:52.141+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:02:52.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:02:52.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.070 seconds
[2024-07-04T10:03:22.621+0000] {processor.py:161} INFO - Started process (PID=3329) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:03:22.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:03:22.626+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:03:22.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:03:22.668+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:03:22.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:03:22.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:03:22.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.071 seconds
[2024-07-04T10:03:53.099+0000] {processor.py:161} INFO - Started process (PID=3388) to work on /opt/airflow/dags/reading_dag.py
[2024-07-04T10:03:53.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/reading_dag.py for tasks to queue
[2024-07-04T10:03:53.104+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:03:53.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:03:53.146+0000] {logging_mixin.py:188} INFO - [2024-07-04T10:03:53.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/reading_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reading_dag.py", line 7, in <module>
    config = Variable.get("hello", deserialize_json=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 146, in get
    obj = json.loads(var_val)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-04T10:03:53.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/reading_dag.py
[2024-07-04T10:03:53.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/reading_dag.py took 0.087 seconds
